/**
 * *****************************************************************************
 * Copyright (c) 2013 -- WPI Suite
 * <p>
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * <p>
 *****************************************************************************
 */
package edu.wpi.cs.wpisuitetng.modules.planningpoker.view.main;

import java.awt.CardLayout;

import edu.wpi.cs.wpisuitetng.modules.planningpoker.model.GameModel;

/**
 * The requirements panel of the planning poker GUI
 * <p>
 * 
 * @author llhunker, dbtrue
 */
public class GameDescriptionPanel extends javax.swing.JPanel {
    
    /**
     *
     */
    private static final long serialVersionUID = 7579915917240962935L;
    private CompletedGamePanel completed;
    private UncompletedGameDescriptionPanel uncompleted;
    
    /**
     * Creates new form NewJPanel
     */
    public GameDescriptionPanel() {
        setLayout(new CardLayout(0, 0));
        
        uncompleted = new UncompletedGameDescriptionPanel();
        add(uncompleted, "uncompleted");
        
        completed = new CompletedGamePanel();
        add(completed, "completed");
        initComponents();
    }
    
    public void setGame(GameModel game) {
        if (game.isEnded()) {
            ((CardLayout) getLayout()).show(this, "completed");
            completed.setGame(game);
        } else {
            ((CardLayout) getLayout()).show(this, "uncompleted");
            uncompleted.setGame(game);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    
    protected CompletedGamePanel getCompleted() {
        return completed;
    }
    
    protected UncompletedGameDescriptionPanel getUncompleted() {
        return uncompleted;
    }
}