/**
 * *****************************************************************************
 * Copyright (c) 2013 -- WPI Suite
 * <p>
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * <p>
 *****************************************************************************
 */
package edu.wpi.cs.wpisuitetng.modules.planningpoker.view.main;

import javax.swing.DefaultListModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import javax.swing.LayoutStyle.ComponentPlacement;

import edu.wpi.cs.wpisuitetng.modules.planningpoker.model.GameModel;

/**
 * The requirements panel of the planning poker GUI
 * <p>
 * 
 * @author llhunker, dbtrue
 */
public class UncompletedGameDescriptionPanel extends javax.swing.JPanel {
    
    /**
     *
     */
    private static final long serialVersionUID = 7579915917240962935L;
    
    /**
     * Creates new form NewJPanel
     */
    public UncompletedGameDescriptionPanel() {
        initComponents();
    }
    
    public void setGame(GameModel game) {
        setGameName(game.getName());
        setDescriptionText(game.getDescription());
        // DefaultListModel<String> listModel = new DefaultListModel<>();
        // listModel.addElement(element);
        // getParticipantsList().setModel(listModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        nameLabel = new javax.swing.JLabel();
        nameLabel.setText("Name:");
        
        gameName = new JLabel("");
        
        JLabel lblParticipants = new JLabel("Participants:");
        
        JScrollPane scrollPane = new JScrollPane();
        
        JLabel lblProgress = new JLabel("Requirement Progress:");
        
        progressBar = new JProgressBar();
        
        progressLabel = new JLabel("0/0");
        
        JLabel lblDescription = new JLabel("Description:");
        
        JScrollPane scrollPane_1 = new JScrollPane();
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(layout
                .createParallelGroup(Alignment.TRAILING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        layout.createParallelGroup(
                                                Alignment.LEADING)
                                                .addComponent(
                                                        scrollPane_1,
                                                        GroupLayout.DEFAULT_SIZE,
                                                        430, Short.MAX_VALUE)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addComponent(
                                                                        nameLabel)
                                                                .addPreferredGap(
                                                                        ComponentPlacement.RELATED)
                                                                .addComponent(
                                                                        gameName))
                                                .addComponent(
                                                        scrollPane,
                                                        GroupLayout.DEFAULT_SIZE,
                                                        430, Short.MAX_VALUE)
                                                .addComponent(lblParticipants)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addComponent(
                                                                        lblProgress)
                                                                .addPreferredGap(
                                                                        ComponentPlacement.RELATED)
                                                                .addComponent(
                                                                        progressBar,
                                                                        GroupLayout.PREFERRED_SIZE,
                                                                        GroupLayout.DEFAULT_SIZE,
                                                                        GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        ComponentPlacement.RELATED)
                                                                .addComponent(
                                                                        progressLabel))
                                                .addComponent(lblDescription))
                                .addContainerGap()));
        layout.setVerticalGroup(layout
                .createParallelGroup(Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        layout.createParallelGroup(
                                                Alignment.BASELINE)
                                                .addComponent(nameLabel)
                                                .addComponent(gameName))
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addComponent(lblDescription)
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addComponent(scrollPane_1,
                                        GroupLayout.DEFAULT_SIZE, 59,
                                        Short.MAX_VALUE)
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addComponent(lblParticipants)
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addComponent(scrollPane,
                                        GroupLayout.PREFERRED_SIZE, 77,
                                        GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(ComponentPlacement.UNRELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                Alignment.LEADING)
                                                .addComponent(lblProgress)
                                                .addComponent(
                                                        progressBar,
                                                        GroupLayout.PREFERRED_SIZE,
                                                        GroupLayout.DEFAULT_SIZE,
                                                        GroupLayout.PREFERRED_SIZE)
                                                .addComponent(progressLabel))
                                .addGap(62)));
        
        descriptionText = new JTextPane();
        scrollPane_1.setViewportView(descriptionText);
        
        participantsList = new JList<String>();
        participantsList.setModel(new DefaultListModel<String>());
        scrollPane.setViewportView(participantsList);
        setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents
    
    private javax.swing.JLabel nameLabel;
    private JLabel gameName;
    private JTextPane descriptionText;
    private JList<String> participantsList;
    private JProgressBar progressBar;
    private JLabel progressLabel;
    
    protected String getGameName() {
        return gameName.getText();
    }
    
    protected void setGameName(String text) {
        gameName.setText(text);
    }
    
    protected String getDescriptionText() {
        return descriptionText.getText();
    }
    
    protected void setDescriptionText(String text_1) {
        descriptionText.setText(text_1);
    }
    
    protected int getProgressBarValue() {
        return progressBar.getValue();
    }
    
    protected void setProgressBarValue(int value) {
        progressBar.setValue(value);
    }
    
    protected String getProgressLabelText() {
        return progressLabel.getText();
    }
    
    protected void setProgressLabelText(String text_2) {
        progressLabel.setText(text_2);
    }
    
    protected JList<String> getParticipantsList() {
        return participantsList;
    }
}