/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.wpi.cs.wpisuitetng.modules.planningpoker.view.main;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle.ComponentPlacement;

import edu.wpi.cs.wpisuitetng.modules.planningpoker.model.Estimate;
import edu.wpi.cs.wpisuitetng.modules.planningpoker.model.GameRequirementModel;

/**
 * 
 * @author nfbrown
 */
public class VotePanel extends javax.swing.JPanel {
    
    /**
     *
     */
    private static final long serialVersionUID = 6053116033835102214L;
    
    /**
     * Creates new form VotePanel
     */
    public VotePanel() {
        initComponents();
    }
    
    public void setRequirement(GameRequirementModel req) {
        reqDescriptionTextArea.setText(req.getDescription());
        
        
        ArrayList<Estimate> estimates = req.getEstimates();
        
        estimateCardsPanel.removeAll();
        for (Estimate est : estimates) {
            JButton estimate_card = new JButton();
            estimate_card.setText(est.getEstimate() + "");
            estimate_card.setPreferredSize(new Dimension(80, 120));
            estimate_card.addActionListener(new ActionListener() {
                
                @Override
                public void actionPerformed(ActionEvent e) {
                    selectEstimateCard((JButton) e.getSource());
                }
            });
            estimateCardsPanel.add(estimate_card);
        }
        validate();
        repaint();
        
        
        // TODO: make GameRequirementModel have reference to parent game for
        // getting endDate, etc...
    }
    
    private void selectEstimateCard(JButton selected_card_button) {
        // TODO: submit estimate based on selected card
        for (Component c : estimateCardsPanel.getComponents()) {
            ((JButton) c).setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        estimateLabel = new javax.swing.JLabel();
        voteField = new javax.swing.JLabel();
        completedVotesField = new javax.swing.JLabel();
        endsLabel = new javax.swing.JLabel();
        endTimeField = new javax.swing.JLabel();
        votesProgressBar = new javax.swing.JProgressBar();
        
        estimateLabel.setText("Estimate:");
        
        voteField.setText("Votes:");
        
        completedVotesField.setText("0/15");
        
        endsLabel.setText("Ends at:");
        
        endTimeField.setText("3/23 6:00 PM");
        
        JLabel lblRequirement = new JLabel("Requirement:");
        
        JScrollPane scrollPane = new JScrollPane();
        
        JScrollPane scrollPane_1 = new JScrollPane();
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(layout
                .createParallelGroup(Alignment.TRAILING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        layout.createParallelGroup(
                                                Alignment.TRAILING)
                                                .addComponent(
                                                        scrollPane_1,
                                                        Alignment.LEADING,
                                                        GroupLayout.DEFAULT_SIZE,
                                                        585, Short.MAX_VALUE)
                                                .addComponent(
                                                        scrollPane,
                                                        Alignment.LEADING,
                                                        GroupLayout.DEFAULT_SIZE,
                                                        585, Short.MAX_VALUE)
                                                .addGroup(
                                                        Alignment.LEADING,
                                                        layout.createSequentialGroup()
                                                                .addComponent(
                                                                        endsLabel)
                                                                .addPreferredGap(
                                                                        ComponentPlacement.UNRELATED)
                                                                .addComponent(
                                                                        endTimeField))
                                                .addComponent(lblRequirement,
                                                        Alignment.LEADING)
                                                .addGroup(
                                                        Alignment.LEADING,
                                                        layout.createSequentialGroup()
                                                                .addComponent(
                                                                        voteField)
                                                                .addGap(18)
                                                                .addComponent(
                                                                        votesProgressBar,
                                                                        GroupLayout.PREFERRED_SIZE,
                                                                        GroupLayout.DEFAULT_SIZE,
                                                                        GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        ComponentPlacement.RELATED)
                                                                .addComponent(
                                                                        completedVotesField))
                                                .addComponent(estimateLabel,
                                                        Alignment.LEADING))
                                .addContainerGap()));
        layout.setVerticalGroup(layout
                .createParallelGroup(Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblRequirement)
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addComponent(scrollPane,
                                        GroupLayout.PREFERRED_SIZE, 103,
                                        GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                Alignment.TRAILING)
                                                .addGroup(
                                                        layout.createParallelGroup(
                                                                Alignment.BASELINE)
                                                                .addComponent(
                                                                        voteField)
                                                                .addComponent(
                                                                        completedVotesField))
                                                .addComponent(
                                                        votesProgressBar,
                                                        GroupLayout.PREFERRED_SIZE,
                                                        GroupLayout.DEFAULT_SIZE,
                                                        GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                Alignment.BASELINE)
                                                .addComponent(endsLabel)
                                                .addComponent(endTimeField))
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addComponent(estimateLabel)
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addComponent(scrollPane_1,
                                        GroupLayout.DEFAULT_SIZE, 203,
                                        Short.MAX_VALUE).addContainerGap()));
        
        estimateCardsPanel = new JPanel();
        scrollPane_1.setViewportView(estimateCardsPanel);
        estimateCardsPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        
        reqDescriptionTextArea = new JTextArea();
        reqDescriptionTextArea.setText("test");
        scrollPane.setViewportView(reqDescriptionTextArea);
        setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel completedVotesField;
    private javax.swing.JLabel endTimeField;
    private javax.swing.JLabel endsLabel;
    private javax.swing.JLabel estimateLabel;
    private javax.swing.JLabel voteField;
    private javax.swing.JProgressBar votesProgressBar;
    private JTextArea reqDescriptionTextArea;
    private JPanel estimateCardsPanel;
}